### ISSUE TITLE
Add dialog methods

### ISSUE THREAD

**Issue by viniciusfbb** [Embarcadero/DelphiFMX4Python#36]
There is no implementation of dialogs methods, such as ShowMessage or FMX.DialogService methods that are fundamental in the application.

**Comment by lmbelo** [comment]
Hi @viniciusfbb,

We are working on new wrappers and the TDialogService has been included to the roadmap.

**Comment by Priyatham10** [comment]
ShowMessage is wrapped for `DelphiVCL` already where as it'll start working from our next release in DelphiFMX.

**Comment by shaunroselt** [comment]
> ShowMessage is wrapped for `DelphiVCL` already where as it'll start working from our next release in DelphiFMX.

Has this been finished for FMX yet or is it still on the roadmap for a future release?

**Comment by lmbelo** [comment]
It will be available in the next release.

![Screenshot 2023-03-01 at 16 24 09](https://user-images.githubusercontent.com/8376898/222243460-092027b1-cc65-4216-b54e-cbfc57d431f6.png)

**Comment by shaunroselt** [comment]
I tested this with the latest release. It's definitely working. We can close this issue.

Here's a screenshot:

![image](https://github.com/Embarcadero/DelphiFMX4Python/assets/5418178/c3c85f79-2f67-4629-a17b-a989323f2183)


Also answered this question on StackOverflow about it: https://stackoverflow.com/a/76279990/2908017

**Comment by vhanla** [comment]
Does it also include Open and Save dialogs? I'm currently mixing with tkinter's but on Linux they have inconsistent look and size and it leaves a tk window after closing the askdirectory() dialog, and the entire screen is not clickable while that tkinters dialog was showing, and it doesn't support high dpi, that's why it shows so small on 150% (tkinter's issue though)  
![image](https://github.com/Embarcadero/DelphiFMX4Python/assets/1015823/027d7805-8d2b-4660-85dc-3ac59f8e9d28)
